Fix missing `CheckpointManager` import on `torch==2.8` on Aurora
Explicitly, this resolves the:

```bash
Traceback (most recent call last):
  File "/opt/aurora/25.190.0/frameworks/aurora_frameworks-2025.2.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/aurora/25.190.0/frameworks/aurora_frameworks-2025.2.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/lus/flare/projects/AuroraGPT/AuroraGPT-v1/Experiments/AuroraGPT-2B/tt/saforem2/torchtitan/torchtitan/experiments/blendcorpus/train.py", line 21, in <m
odule>
    from torchtitan.components.checkpoint import CheckpointManager
  File "/lus/flare/projects/AuroraGPT/AuroraGPT-v1/Experiments/AuroraGPT-2B/tt/saforem2/torchtitan/torchtitan/components/checkpoint.py", line 26, in <module>
    from torch.distributed.checkpoint._consolidate_hf_safetensors import (
ModuleNotFoundError: No module named 'torch.distributed.checkpoint._consolidate_hf_safetensors'
x4613c1s6b0n0.hsn.cm.aurora.alcf.anl.gov: rank 5 exited with code 1
```

issue when using `torch==2.8` on Aurora